{ config, pkgs, inputs, ...}:
{
  home.packages = with pkgs; [
    gnome.gnome-software
    inputs.prismlauncher.packages.${pkgs.system}.prismlauncher
    steam-run
    kitty
    pamixer
    rofi-wayland
    brightnessctl   
    pwvucontrol
    pkgs.discord
    xfce.thunar 
    firefox
    swww
    vim
    telegram-desktop
    pkgs.dunst
    glib
    libnotify
    font-manager
    font-awesome
    unzip
    vlc
    feh
    git   
    wttrbar
    pkgs.grim
    pkgs.slurp
    pkgs.wl-clipboard
    clang
    htop
    virtualbox
    dotnetCorePackages.sdk_6_0_1xx
  ];
}
