{
  imports = [
    ./cellular-automaton.nix
    ./tailwind-tools.nix
    ./todo-comments.nix
    ./vim-css-color.nix
    ./ts-autotag.nix
    ./autoclose.nix
    ./telescope.nix
    ./markdown.nix
    ./floaterm.nix
    ./hardtime.nix
    ./lualine.nix
    ./neotree.nix
    ./comment.nix
    ./trouble.nix
    ./godot.nix
    ./goyo.nix
    ./nix.nix
    ./lsp.nix
    ./cmp.nix
  ];
}
